### ISSUE TITLE
Frame Skipping and choreographer error. Too much work in Main Thread

### ISSUE THREAD

**Issue by Welborn09** [Diolor/Swipecards#121]
Hello. I am getting frames skipped and choreographer errors with a message 'The application may be doing too much work on its main thread'.

I am wondering if it is possible to move the actual swiping effect to a secondary thread using AsyncTask?
If not what other options are there to free up the main UI?

**Comment by alexwalterbos** [comment]
You cannot move the swipe effect to a secondary thread because all view logic must be executed on the main thread. 

You could [check](http://developer.android.com/tools/performance/debug-gpu-overdraw/index.html) for (possible) overdraw, which can help improve performance. In this case that can be achieved by removing any background behind the card container, or reduce the amount of cards that are loaded simultaniously.

**Comment by raevilman** [comment]
I reduced skipped frame to half by setting MAX_VISIBLE = 2

**Comment by Welborn09** [comment]
Thank you Alex and raevilman. I apologize for the delay in response my notifications didn't go through.  I was able to use the check and made it better.
