### ISSUE TITLE
Disable card vertical movement?

### ISSUE THREAD

**Issue by joaodias** [Diolor/Swipecards#123]
Hi guys ! 
Is it possible somehow to disable the card's vertical movement? 
I mean, when you drag the card, it only allows it to move either right or left. No up or down movement at all and no angle rotation on the card (last one I know is possible with app:rotation_degrees="0").

**Comment by alexwalterbos** [comment]
You can include the library source and disable these lines:

https://github.com/Diolor/Swipecards/blob/master/library/src/main/java/com/lorentzos/flingswipe/FlingCardListener.java#L142
https://github.com/Diolor/Swipecards/blob/master/library/src/main/java/com/lorentzos/flingswipe/FlingCardListener.java#L147
https://github.com/Diolor/Swipecards/blob/master/library/src/main/java/com/lorentzos/flingswipe/FlingCardListener.java#L163

I have not tested this, but that should work since those statements calculate and apply the offset in the y direction.

**Comment by joaodias** [comment]
Thanks! It worked :+1:
