### ISSUE TITLE
Card with scrollview

### ISSUE THREAD

**Issue by franrc** [Diolor/Swipecards#136]
Hi!

I must use an scrollview into the card to show all the information, but the drag action is not possible.

Do you know how can I achieve this?

Thanks!

**Comment by alexwalterbos** [comment]
This happens because the card view consumes all the touch events, which thus never reach the scroll view. To be honest, it sounds like a pretty bad UX to have a scrollview in your cards exactly because of the conflict; when will the user mean to scroll, and when to fling the card? 

If you still want to do this, you'll have to dive into the `OnTouchListener`s by forking this library, and attaching a custom one that decides whether to fling the card or whether to delegate it to the scroll view that's nested in the card.

**Comment by franrc** [comment]
I agree with you, but the client wants to show the entire text in the card. 

Thanks for your answer!

**Comment by martinothamar** [comment]
I currently have a use-case for this. Inside the card there is a vertical ListView. I want the card to capture horizontal scrolling but the ListView keeps grabbing it. I have been trying to detect horizontal swiping on the card layout and then returning false on the intercept touch method, but its clearly not the right way. How would I go about this?

**Comment by alexwalterbos** [comment]
I can't really help you here:

1. because I think you can never implement this in a way that works for everyone, e.g. everyone swipes differently and a horizontal swipe often has a vertical offset too; you can't possibly handle all cases.
1. because I'm convinced these gestures (scrolling vs swiping the same view) is just not going to give you a UX that's clear and understandable for all your users.

If you're really keen on doing this, the answer lies in that `OnTouchListener` and handling the event or passing it along. I can't help you with the exact parameters.

**Comment by mwshubham** [comment]
Does the feature still in wontfix.
